defaults:
  - env: polishing
  - controller: position_var #position_var #position_var_sweep
  - task_config: force_control_4
  - algorithm: sac
  - _self_  

root_dir: "./exp"
dir: ${root_dir}/${env.name}/${now:%Y.%m.%d}/${now:%H%M%S}
project: sb3
use_wandb: True
seed: 9
experiment: ResRL_s_${seed}_r_${task_config.reward_mode}_ag_cfg_${controller.agent_config}

hydra:
  run:
    dir: ${dir}
