defaults:
  - env: polishing
  - controller: position_var #position_var #position_var_sweep
  - task_config: force_control_4
  - algorithm: sac
  - _self_  

root_dir: "./exp"
dir: ${root_dir}/${env.name}/${now:%Y.%m.%d}/${now:%H%M%S}
project: sb3
use_wandb: false
seed: 9
experiment: full_s_${seed}_f_9

hydra:
  run:
    dir: ${dir}
