
# settings for quadratic reward
arm_limit_collision_penalty: 0  # penalty for reaching joint limit or arm collision (except the wiping tool) with the table
#ee_accel_penalty: 0  # penalty for large end-effector accelerations
max_vel: 0.015
#general_penalty: -3
#position_track_multiplier: 10

##--------------------------------------------------------------------------------------------------------------------------------------##
                                                        # force parameters
##--------------------------------------------------------------------------------------------------------------------------------------##

target_force: 5
f_cap: 7.5
f_safe: 10


reward_calc_lower_limit_force: 0
reward_calc_upper_limit_force: 10
target_xvel: 0
reward_calc_lower_limit_xvel: -0.04
reward_calc_upper_limit_xvel: 0.04
target_xdist : 0 # - Funktioniert nur für gearde Linien in x Richtung!!
reward_calc_lower_limit_xdist: -0.008
reward_calc_upper_limit_xdist: 0.008
target_yvel: 0.07
reward_calc_lower_limit_yvel: 0.12
reward_calc_upper_limit_yvel: 0.02

reward_calc_min_force_for_contact: 1
reward_done: 25

reward_calc_c_force: -0.4
reward_calc_c_xvel: -0.1
reward_calc_c_xdist: -0.1
reward_calc_c_yvel: -0.5
reward_calc_c_contact: 0.6 #should be 1 to get the full -1 to 1 reward range
reward_calc_c_done: 1
# The sum of *_c_* values without c_done should be 0. Scaling factors for penalties have to be negative!

# settings for quadratic reward (ToDo should prob. go)
#arm_limit_collision_penalty: -10.0  # penalty for reaching joint limit or arm collision (except the wiping tool) with the table


##--------------------------------------------------------------------------------------------------------------------------------------##

#distance_multiplier: 1  # multiplier for the dense reward inversely proportional to the mean location of the pegs to wipe
#distance_th_multiplier: 5.0  # multiplier in the tanh function for the aforementioned reward
# settings for table top
table_full_size: [0.5, 0.8, 0.05]  # Size of tabletop
table_offset: [0.15, 0, 0.9]  # Offset of table (z dimension defines max height of table)
table_friction: [0.03, 0.005, 0.0001]  # Friction parameters for the table
table_friction_std: 0  # Standard deviation to sample different friction parameters for the table each episode
table_height: 0  # Additional height of the table over the default location
table_height_std: 0  # Standard deviation to sample different heigths of the table each episode
line_width: 0.04  # Width of the line to wipe (diameter of the pegs)
two_clusters: False  # if the dirt to wipe is one continuous line or two
coverage_factor: 0.6  # how much of the table surface we cover
num_markers: 100  # How many particles of dirt to generate in the environment
# settings for thresholds
contact_threshold: 0.30  # Minimum eef force to qualify as contact [N]
pressure_threshold: 1  # force threshold (N) to overcome to get increased contact wiping reward
pressure_threshold_max: 2 # maximum force allowed (N)

# misc settings
print_results: False  # Whether to print results or not
get_info: True  # Whether to grab info after each env step if not
use_robot_obs: True  # if we use robot observations (proprioception) as input to the policy
use_contact_obs: True  # if we use a binary observation for whether robot is in contact or not
early_terminations: True  # Whether we allow for early terminations or not
use_condensed_obj_obs: False  # Whether to use condensed object observation representation (only applicable if obj obs is active)
use_object_obs: True
use_force_obs: True
no_contact_penalty: 0
force_multiplier: 5 # 0.5
dist_th: 0.02
indent: 0.015
reward_mode: 2
clip: 0.02
min_vel: 0.003
task_complete_reward: 100
