program: /hpcwork/ru745256/master_thesis/7_8/robosuite/robosuite/main/hydra_sweep.py
name: reward_2_vel
method: bayes
metric:
  name: Wipe/Return
  goal: maximize
parameters:
  Kp_xy: 
    distribution: 'int_uniform'
    max: 300
    min: 0
  Kp_z: 
    distribution: 'int_uniform'
    max: 300
    min: 0
  Kp_or_xy: 
    distribution: 'int_uniform'
    max: 300
    min: 0
  Kp_or_z:
    value: 20  
  Kd_xy: 
    distribution: 'int_uniform'
    max: 10
    min: 0
  Kd_z: 
    distribution: 'int_uniform'
    max: 10
    min: 0
  Kd_or_xy: 
    distribution: 'int_uniform'
    max: 10
    min: 0
  Kd_or_z:
    value: 1

  indent:
    distribution: 'uniform'
    max: 0.3
    min: 0.001  