program: /hpcwork/ru745256/master_thesis/30_6/robosuite/robosuite/main/sweep_orientation.py
method: bayes
metric:
  name: Wipe/Return
  goal: maximize
parameters:
  Kp_or: 
    distribution: 'int_uniform'
    max: 300
    min: 0
  Kd_or: 
    distribution: 'int_uniform'
    max: 10
    min: 0  