  type: "OSC_POSITION"
  input_max: 1
  input_min: -1
  output_max: [0.02, 0.02, 0.02]
  output_min: [-0.02, -0.02, -0.02]
  kp: 40
  damping_ratio: 3
  impedance_mode: "variable"
  kp_limits: [0, 400]
  damping_ratio_limits: [1, 10]
  position_limits: null
  control_delta: True
  interpolation: null
  ramp_ratio: 0.2
  agent_config: 0